export const TRADING_PAIRS = [
  'BTC/USDT',
  'ETH/USDT',
  'USDC/USDT',
  'SOL/USDT',
  'XRP/USDT',
  'BNB/USDT',
  'DOGE/USDT',
  'ADA/USDT',
  'LINK/USDT',
  'BNB/USD',
  'BNB/EUR',
  'BNB/TRY',
  'BNB/BRL',
  'BNB/AUD',
  'BTC/USD',
  'BTC/EUR',
  'BTC/TRY',
  'BTC/BRL',
  'BTC/AUD',
  'ETH/USD',
  'ETH/EUR',
  'ETH/TRY',
  'ETH/BRL',
  'ETH/AUD',
  'SOL/USD',
  'SOL/EUR',
  'XRP/USD',
  'XRP/EUR',
  'ADA/USD',
  'ADA/EUR',
  'DOGE/USD',
  'DOGE/EUR',
  'LINK/USD',
  'LINK/EUR',
  'BNB/BTC',
  'BNB/ETH',
  'BNB/ADA',
  'BNB/BUSD',
  'BNB/USDC',
] as const;

export type TradingPair = (typeof TRADING_PAIRS)[number];
